services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ds-project:latest
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
