[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=64.0.0", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[project]
name = "DS_project"
version = "0.0.1"
description = "Data Science project template"
packages = [{include = "src"}]
authors = [
  {name = "Mikhail S.", email = "fortis3000@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "pydantic==2.7.1"
]

[project.optional-dependencies]
dev = ["pytest==8.2.0"]
lint = [
  "ruff==0.13.0"
]

[tool.ruff]
# Formatting
line-length = 100
exclude = [".pytest_cache", "**/__pycache__/", "**/*.ipynb_checkpoints/", "*.ipynb"]
# Linting
lint.extend-select = ["F", "I", "PL", "N"]
lint.extend-ignore = ["D", "E501", "PLR0913", "E402", "C403","F405", "E203","E731", "E712"]

[tool.ruff.lint.isort]
case-sensitive = true