[tool.poetry]
name = "DS project"
version = "0.0.1"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.codestyle.dependencies]
black = "23.3.0"
isort = "5.12.0"
pylint = "2.17.3"
