name: 'Linting'

on: push

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.7.0"

jobs:
  linting:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.py

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: "dev_env"
      
      - name: Compile and install environment
        shell: bash
        id: uv
        run: |
          uv --version
          uv pip compile pyproject.toml -o requirements.txt
          uv pip sync requirements.txt

      - name: Checking linting with ruff
        shell: bash
        id: ruff-linting
        run: ruff check .
      
      - name: Checking formatting with ruff
        shell: bash
        id: ruff-format
        run: ruff format --check .
      
      - name: Check all steps
        shell: bash
        if: steps.ruff-linting.outcome != 'success'  || steps.ruff-format.outcome != 'success'
        run: |
          if [ "$steps.ruff-linting.outcome" != "success" ]; then
            echo "Sorting imports with isort failed."
          fi
          
          if [ "$steps.ruff-format.outcome" != "success" ]; then
            echo "Formatting with black failed."
          fi

          exit 1