name: 'CI'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  isort_formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2
      - name: poetry installation check
        run: poetry --version  
      - name: Install codestyle dependencies
        run: poetry install --only codestyle
      - name: checking with isort
        run: python -m isort --check-only  .
      - name: checking with black
        run: python -m black --check --config pyproject.toml .
      - name: checking with pylint
        run: python -m pylint .