name: 'CI'

on:
  workflow_dispatch:
    paths: 
      - "**/*.py"
  pull_request:
    paths: 
      - "**/*.py"

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.4.0"

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Python installation check
        run: pip --version

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Poetry installation check
        run: poetry --version  

      - name: Install codestyle dependencies
        run: poetry install --only codestyle

      - name: Checking with isort
        continue-on-error: true
        run: poetry run isort --check-only  .

      - name: Checking with black
        continue-on-error: true
        run: poetry run black --check --config pyproject.toml .

      - name: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: List all changed files
        run: |
          for file in ${{ steps.file_changes.outputs.files_modified }}; do
            echo "$file was changed"
          done

      - name: Checking with pylint
        continue-on-error: true
        run: |
          if [ -z ${{ steps.file_changes.outputs.files_modified }} ]
          then 
            echo "There are no modified Python files."
          else
            poetry run pylint src/
          fi