name: 'CI'

on:
  workflow_dispatch:
  # workflow_call
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  POETRY_VERSION: 1.2.0

jobs:
  isort_formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
      - uses: actions/checkout@v3

      - name: Installing Python
      - uses: actions/setup-python@v4

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        # with:
        #   poetry-version: 1.4.2

      - name: poetry installation check
        run: poetry --version  

      - name: Install codestyle dependencies
        run: poetry install --only codestyle

      - name: Checking with isort
        run: poetry run isort --check-only  .

      - name: Checking with black
        run: poetry run black --check --config pyproject.toml .

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          files: |
          **/*.{py}

      - name: List all changed files
        run: |
          for file in ${{ steps.file_changes.outputs.files_modified }}; do
            echo "$file was changed"
          done

      - name: Checking with pylint
        run: |
          if [-z ${{ steps.file_changes.outputs.files_modified }}]
          then 
          echo "There are no modified Python files."
          else
            poetry run pylint src/
          fi