name: 'Linting'

on: push

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.7.0"

jobs:
  linting:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.py

      - name: Early exit
        continue-on-error: true
        run: |
          if [ "${{ steps.changed-files.outputs.all_changed_files }}" = "[]" ]
          then 
            echo "There are no modified Python files."
            exit 0;
          else
            echo "Python files discovered, starting a job."
          fi

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          cache: 'poetry'

      - name: Install codestyle dependencies
        run: poetry install --only codestyle

      - name: Checking the order of imports
        shell: bash
        id: isort
        continue-on-error: true
        run: |
           isort --version
           isort -v --settings-file ./pyproject.toml .

      - name: Checking formatting with black
        shell: bash
        id: black
        run: |
           black --version
           black -v .

      - name: Linting with pylint
        shell: bash
        id: pylint
        run: |
           pylint --version
           pylint "${{ steps.changed-files.outputs.all_changed_files }}"