name: 'CI'

# checking only .py file in the repo
on:
  workflow_dispatch:
    paths: 
      - "**/*.py"
  pull_request:
    paths: 
      - "**/*.py"

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

env:
  PYTHON_VERSION: "3.10.11"
  POETRY_VERSION: "1.4.2"

jobs:
  linting:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmd: poetry run isort --check-only
            name: isort
          - cmd: poetry run black --check
            name: black
          - cmd: poetry run pylint
            name: pylint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          cache: 'poetry'

      - name: Install codestyle dependencies
        run: poetry install --only codestyle

      - name: List of files changed
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: ${{matrix.name}}
        continue-on-error: true
        run: |
          if [ "${{ steps.file_changes.outputs.files_modified }}" = "[]" ]
          then 
            echo "There are no modified Python files."
          else
            ${{matrix.cmd}} ${{ steps.file_changes.outputs.files_modified }}
          fi

      # - name: Checking with isort
      #   continue-on-error: true
      #   run: poetry run isort --check-only .

      # - name: Checking with black
      #   continue-on-error: true
      #   run: poetry run black --check .

      # - name: Checking with pylint
      #   continue-on-error: true
      #   run: |
      #     if [ -z ${{ steps.file_changes.outputs.files_modified }} ]
      #     then 
      #       echo "There are no modified Python files."
      #     else
      #       poetry run pylint ${{ steps.file_changes.outputs.files_modified }}
      #     fi