name: 'Linting'

# checking only .py file in the repo
on: push

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.7.0"

jobs:
  linting:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmd: poetry run python -m isort --check-only .
            name: isort
          - cmd: poetry run python -m black .
            name: black
          - cmd: poetry run python -m pylint .
            name: pylint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # TODO: early exit
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.py

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          cache: 'poetry'

      - name: Install codestyle dependencies
        run: poetry install --only codestyle

      - name: ${{matrix.name}}
        continue-on-error: false
        run: |
          if [ "${{ steps.changed-files.outputs.all_changed_files }}" = "[]" ]
          then 
            echo "There are no modified Python files."
          else
            ${{matrix.cmd}}
          fi